# Generated by Django 6.0.4 on 2026-05-04 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_alter_project_created_by_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes_task', to='project_management.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
