# Generated by Django 6.0.4 on 2026-05-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_progressnotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgressNotes',
            new_name='ProgressNote',
        ),
    ]
