# Generated by Django 6.0.4 on 2026-05-04 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_rename_progressnotes_progressnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
